# Generated by Django 5.0.1 on 2024-01-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_match_match_id_alter_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
    ]
