# Generated by Django 5.0.1 on 2024-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
