# Generated by Django 5.0.1 on 2024-01-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
