# Generated by Django 5.0.1 on 2024-01-23 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_player_player_id_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
    ]
